apiVersion: apps/v1
kind: Deployment
metadata:
  name: grabber
  namespace: default
  labels:
    app: grabber
spec:
  selector:
    matchLabels:
      app: grabber
  replicas: 1
  template:
    metadata:
      labels:
        app: grabber
    spec:
      containers:
        - name: grabber
          image: registry.registry.lan/grabber:release